# Generated by Django 4.1.1 on 2022-09-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=3)),
                ('process', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(max_length=16)),
                ('ingr_name', models.CharField(max_length=64)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('rec_id', models.ManyToManyField(related_name='receipts', to='cooking.receipts')),
            ],
        ),
    ]
