# Generated by Django 4.1.1 on 2022-10-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=64)),
                ('category_id', models.ManyToManyField(related_name='category', to='cooking.receipts')),
            ],
        ),
    ]
