# Generated by Django 4.1.1 on 2022-10-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_category'),
        ('cooking', '0003_rename_receipts_receipt'),
    ]

    operations = [
    ]
