# Generated by Django 4.1.1 on 2022-10-14 23:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cooking", "0003_rename_receipts_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptrating",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="cooking.receipt",
            ),
        ),
        migrations.AlterField(
            model_name="receiptrating",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="receiptrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
