# Generated by Django 4.1.1 on 2022-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_merge_0002_category_0003_rename_receipts_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.ManyToManyField(related_name='category', to='cooking.receipt'),
        ),
    ]
